// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination mock_client.go -package apiclient
//

// Package apiclient is a generated GoMock package.
package apiclient

import (
	dto "TestTaskJustPay/services/ingest/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// SendDisputeUpdate mocks base method.
func (m *MockClient) SendDisputeUpdate(ctx context.Context, req dto.DisputeUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDisputeUpdate", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDisputeUpdate indicates an expected call of SendDisputeUpdate.
func (mr *MockClientMockRecorder) SendDisputeUpdate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDisputeUpdate", reflect.TypeOf((*MockClient)(nil).SendDisputeUpdate), ctx, req)
}

// SendOrderUpdate mocks base method.
func (m *MockClient) SendOrderUpdate(ctx context.Context, req dto.OrderUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOrderUpdate", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOrderUpdate indicates an expected call of SendOrderUpdate.
func (mr *MockClientMockRecorder) SendOrderUpdate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOrderUpdate", reflect.TypeOf((*MockClient)(nil).SendOrderUpdate), ctx, req)
}

// SendPaymentWebhook mocks base method.
func (m *MockClient) SendPaymentWebhook(ctx context.Context, req dto.PaymentWebhookRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPaymentWebhook", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPaymentWebhook indicates an expected call of SendPaymentWebhook.
func (mr *MockClientMockRecorder) SendPaymentWebhook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentWebhook", reflect.TypeOf((*MockClient)(nil).SendPaymentWebhook), ctx, req)
}
