FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the Ingest binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /ingest ./cmd/ingest

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /ingest /ingest

ENTRYPOINT ["/ingest"]
