// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"TestTaskJustPay/src/api"
	"TestTaskJustPay/src/api/handlers"
	"TestTaskJustPay/src/app"
	"TestTaskJustPay/src/service"
)

// Injectors from wire.go:

func InitServer() *app.Server {
	engine := app.NewGinEngine()
	iOrderService := service.NewOrderService()
	orderHandler := handlers.NewOrderHandler(iOrderService)
	router := api.NewRouter(orderHandler)
	server := app.NewServer(engine, router)
	return server
}
