// Code generated by MockGen. DO NOT EDIT.
// Source: pg_inbox_repo.go
//
// Generated by this command:
//
//	mockgen -source pg_inbox_repo.go -destination mock_inbox_repo.go -package inbox
//

// Package inbox is a generated GoMock package.
package inbox

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInboxRepo is a mock of InboxRepo interface.
type MockInboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInboxRepoMockRecorder
	isgomock struct{}
}

// MockInboxRepoMockRecorder is the mock recorder for MockInboxRepo.
type MockInboxRepoMockRecorder struct {
	mock *MockInboxRepo
}

// NewMockInboxRepo creates a new mock instance.
func NewMockInboxRepo(ctrl *gomock.Controller) *MockInboxRepo {
	mock := &MockInboxRepo{ctrl: ctrl}
	mock.recorder = &MockInboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxRepo) EXPECT() *MockInboxRepoMockRecorder {
	return m.recorder
}

// FetchPending mocks base method.
func (m *MockInboxRepo) FetchPending(ctx context.Context, limit int) ([]InboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPending", ctx, limit)
	ret0, _ := ret[0].([]InboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPending indicates an expected call of FetchPending.
func (mr *MockInboxRepoMockRecorder) FetchPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPending", reflect.TypeOf((*MockInboxRepo)(nil).FetchPending), ctx, limit)
}

// MarkFailed mocks base method.
func (m *MockInboxRepo) MarkFailed(ctx context.Context, id, errMsg string, maxRetries int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errMsg, maxRetries)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockInboxRepoMockRecorder) MarkFailed(ctx, id, errMsg, maxRetries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockInboxRepo)(nil).MarkFailed), ctx, id, errMsg, maxRetries)
}

// MarkProcessed mocks base method.
func (m *MockInboxRepo) MarkProcessed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockInboxRepoMockRecorder) MarkProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockInboxRepo)(nil).MarkProcessed), ctx, id)
}

// Store mocks base method.
func (m *MockInboxRepo) Store(ctx context.Context, msg NewInboxMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockInboxRepoMockRecorder) Store(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockInboxRepo)(nil).Store), ctx, msg)
}
