// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source repo.go -destination mock_repo.go -package dispute
//

// Package dispute is a generated GoMock package.
package dispute

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDisputeRepo is a mock of DisputeRepo interface.
type MockDisputeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDisputeRepoMockRecorder
	isgomock struct{}
}

// MockDisputeRepoMockRecorder is the mock recorder for MockDisputeRepo.
type MockDisputeRepoMockRecorder struct {
	mock *MockDisputeRepo
}

// NewMockDisputeRepo creates a new mock instance.
func NewMockDisputeRepo(ctrl *gomock.Controller) *MockDisputeRepo {
	mock := &MockDisputeRepo{ctrl: ctrl}
	mock.recorder = &MockDisputeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisputeRepo) EXPECT() *MockDisputeRepoMockRecorder {
	return m.recorder
}

// CreateDispute mocks base method.
func (m *MockDisputeRepo) CreateDispute(ctx context.Context, dispute NewDispute) (*Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDispute", ctx, dispute)
	ret0, _ := ret[0].(*Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDispute indicates an expected call of CreateDispute.
func (mr *MockDisputeRepoMockRecorder) CreateDispute(ctx, dispute any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDispute", reflect.TypeOf((*MockDisputeRepo)(nil).CreateDispute), ctx, dispute)
}

// GetDisputeByID mocks base method.
func (m *MockDisputeRepo) GetDisputeByID(ctx context.Context, disputeID string) (*Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisputeByID", ctx, disputeID)
	ret0, _ := ret[0].(*Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisputeByID indicates an expected call of GetDisputeByID.
func (mr *MockDisputeRepoMockRecorder) GetDisputeByID(ctx, disputeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisputeByID", reflect.TypeOf((*MockDisputeRepo)(nil).GetDisputeByID), ctx, disputeID)
}

// GetDisputeByOrderID mocks base method.
func (m *MockDisputeRepo) GetDisputeByOrderID(ctx context.Context, orderID string) (*Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisputeByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisputeByOrderID indicates an expected call of GetDisputeByOrderID.
func (mr *MockDisputeRepoMockRecorder) GetDisputeByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisputeByOrderID", reflect.TypeOf((*MockDisputeRepo)(nil).GetDisputeByOrderID), ctx, orderID)
}

// GetDisputes mocks base method.
func (m *MockDisputeRepo) GetDisputes(ctx context.Context) ([]Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisputes", ctx)
	ret0, _ := ret[0].([]Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisputes indicates an expected call of GetDisputes.
func (mr *MockDisputeRepoMockRecorder) GetDisputes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisputes", reflect.TypeOf((*MockDisputeRepo)(nil).GetDisputes), ctx)
}

// GetEvidence mocks base method.
func (m *MockDisputeRepo) GetEvidence(ctx context.Context, disputeID string) (*Evidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvidence", ctx, disputeID)
	ret0, _ := ret[0].(*Evidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvidence indicates an expected call of GetEvidence.
func (mr *MockDisputeRepoMockRecorder) GetEvidence(ctx, disputeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvidence", reflect.TypeOf((*MockDisputeRepo)(nil).GetEvidence), ctx, disputeID)
}

// UpdateDispute mocks base method.
func (m *MockDisputeRepo) UpdateDispute(ctx context.Context, dispute Dispute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDispute", ctx, dispute)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDispute indicates an expected call of UpdateDispute.
func (mr *MockDisputeRepoMockRecorder) UpdateDispute(ctx, dispute any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDispute", reflect.TypeOf((*MockDisputeRepo)(nil).UpdateDispute), ctx, dispute)
}

// UpsertEvidence mocks base method.
func (m *MockDisputeRepo) UpsertEvidence(ctx context.Context, disputeID string, upsert EvidenceUpsert) (*Evidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEvidence", ctx, disputeID, upsert)
	ret0, _ := ret[0].(*Evidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEvidence indicates an expected call of UpsertEvidence.
func (mr *MockDisputeRepoMockRecorder) UpsertEvidence(ctx, disputeID, upsert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEvidence", reflect.TypeOf((*MockDisputeRepo)(nil).UpsertEvidence), ctx, disputeID, upsert)
}
